language: python
python: 3.5
install:
 - pip3 install coverage
 - pip3 install pytest pytest-cov
script:
 - python3 -m pytest --cov=./
 - python3 -m coverage run test_rpn.py
 - python3 -m coverage report
